name: 更新友链
description: 更新博客友链
author: frg2089

inputs:
  gitea-server:
    description: Gitea Server URL
    required: true
  gitea-token:
    description: Gitea Token
    required: true
  gitea-owner:
    description: Gitea Owner
    required: true
  gitea-repo:
    description: Gitea Repo
    required: true
  pr-data:
    description: Pull Request Body
    required: true

runs:
  using: node20
  main: dist/index.js
