name: 更新友链
description: 更新博客友链
author: frg2089

inputs:
  gitea-server:
    description: Gitea Server URL
    required: true
  gitea-token:
    description: Gitea Token
    required: true
  gitea-owner:
    description: Gitea Owner
    required: true
  gitea-repo:
    description: Gitea Repo
    required: true
  local-repo:
    description: 本地仓库位置
    required: true
  github-token:
    description: Github Token
    required: true
    default: ${{ github.token }}
  target:
    description: 博客友链目标文件
    required: true
  links:
    description: 链接
    required: true

runs:
  using: composite
  steps:
    - name: 签出分支
      working-directory: ${{ inputs.local-repo }}
      shell: pwsh
      run: git checkout -b links/gh#${{ github.event.issue.number }}
    - name: 设置提交人信息
      working-directory: ${{ inputs.local-repo }}
      shell: pwsh
      run: |-
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: 修改文件
      id: modify
      shell: node20
      run: ./dist/index.js --pre
    - name: 创建提交
      working-directory: ${{ inputs.local-repo }}
      shell: pwsh
      run: |-
        git add .
        git commit -m "${{ steps.modify.outputs.message }}"
        git push "${{ steps.modify.outputs.token-url }}" "${{ steps.modify.outputs.branch }}" --force
    - name: 创建 PR
      shell: node20
      run: ./dist/index.js
