name: 更新友链
description: 更新博客友链
author: frg2089

inputs:
  target:
    description: 要更新的文件路径
    required: true
  links:
    description: 链接
    required: true

runs:
  using: node20
  main: dist/index.js
