name: 更新友链
description: 更新博客友链
author: frg2089

inputs:
  gitea-server:
    description: Gitea Server URL
    required: true
  gitea-token:
    description: Gitea Token
    required: true
  gitea-owner:
    description: Gitea Owner
    required: true
  gitea-repo:
    description: Gitea Repo
    required: true
  github-token:
    description: Github Token
    required: true
    default: ${{ github.token }}
  target:
    description: 博客友链目标文件
    required: true
  links:
    description: 链接
    required: true

runs:
  using: node20
  main: dist/index.js
