name: 更新博客友链

on:
  issues:
    types:
      - opened
      - edited
      # - closed
      # - reopened

jobs:
  validate_issue:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      OWNER: AgxCOy
      REPO: blogs
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    permissions:
      issues: write
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: 搭建环境
        run: pnpm install && pnpm -r build

      - name: 检查 Issue
        id: check
        uses: ./.github/actions/check

      - name: 递交友链信息
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.BLOGS_PAT }}
        run: |-
          $payload = @{
            event_type     = "bloglink-request"
            client_payload = @{
                ISSUE_NUMBER = '${{ github.event.issue.number }}'
                LINK         = '${{ steps.check.outputs.links }}'
                MSG          = '${{ steps.check.outputs.message }}'
                PR_OPTS      = '${{ steps.check.outputs.pr-data }}'
            }
          }
          $payload | ConvertTo-Json -Depth 3 | gh api /repos/AgxCOy/blogs/dispatches --input -

      - name: 评论 :)
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner
            const repo = context.repo.repo
            const body = "🎉 已提交友链申请！可以去 [AgxCOy/blogs](https://github.com/AgxCOy/blogs/pulls) 看看进展喵。"
            const existing_comment = comments.find((c) => c.user.login === 'github-actions[bot]');
            if (existing_comment) {
              core.info(`Updating comment ${existing_comment.id}`);
              await github.rest.issues.updateComment({repo, owner, comment_id: existing_comment.id, body});
            } else {
              core.info(`Creating a comment`);
              await github.rest.issues.createComment({repo, owner, context.payload.issue.number, body});
            }
