name: 更新博客友链

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened

defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GITEA_SERVER_URL: https://git.liteyuki.org
      GITEA_SERVER_TOKEN: ${{ secrets.GITEA_SERVER_TOKEN }}
      GITEA_OWNER: AgxCOy
      GITEA_REPO: blogs
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 构建
        run: pnpm -r build

      - name: 检查 Issue
        id: check
        uses: ./.github/actions/check
        with:
          gitea-server: ${{ env.GITEA_SERVER_URL }} 
          gitea-token: ${{ env.GITEA_SERVER_TOKEN }}
          gitea-owner: ${{ env.GITEA_OWNER }}
          gitea-repo: ${{ env.GITEA_REPO }}

      - name: 签出博客仓库
        id: blog
        shell: pwsh
        run: |-
          git clone "${{ env.GITEA_SERVER_URL }}/${{ env.GITEA_OWNER }}/${{ env.GITEA_REPO }}.git"
          Set-Location blogs
          git checkout -b "${{ steps.check.outputs.branch }}"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          Write-Output "BLOG_PATH=$($PWD.Path)" >> $env:GITHUB_OUTPUT
      - name: 更新友链
        id: update
        uses: ./.github/actions/update
        with:
          target: ${{ steps.blog.outputs.BLOG_PATH }}/src/friends.json
          links: ${{ steps.check.outputs.links }}
      - name: 创建提交
        working-directory: ${{ steps.blog.outputs.BLOG_PATH }}
        shell: pwsh
        run: |-
          git add .
          git commit -m "${{ steps.check.outputs.message }}"
          git push "${{ steps.check.outputs.token-url }}" "${{ steps.check.outputs.branch }}" --force
      - name: 创建合并请求
        uses: ./.github/actions/pull
        with:
          gitea-server: ${{ env.GITEA_SERVER_URL }} 
          gitea-token: ${{ env.GITEA_SERVER_TOKEN }}
          gitea-owner: ${{ env.GITEA_OWNER }}
          gitea-repo: ${{ env.GITEA_REPO }}
          pr-data: ${{ steps.check.outputs.pr-data }}